from utils.consts import (
    MONGO_HOST_ENV,
    MONGO_PORT_ENV,
    AUTO_ACCEPT_NEW_USERS_ENV,
    MONGO_MAX_USERS_ENV,
    ENVIRONMENT_DEFAULTS,
)

# for dev
MONGO_HOST_DEFAULT_VALUE = ENVIRONMENT_DEFAULTS[MONGO_HOST_ENV]
MONGO_PORT_DEFAULT_VALUE = ENVIRONMENT_DEFAULTS[MONGO_PORT_ENV]

AUTO_ACCEPT_NEW_USERS_DEFAULT = ENVIRONMENT_DEFAULTS[AUTO_ACCEPT_NEW_USERS_ENV]
MONGO_MAX_USERS_DEFAULT = ENVIRONMENT_DEFAULTS[MONGO_MAX_USERS_ENV]

USERS_TABLE_NAME = 'users'
