MONGO_HOST_ENV = 'MONGO_SERVICE_HOST'
MONGO_PORT_ENV = 'MONGO_SERVICE_PORT'

# for dev
MONGO_HOST_DEFAULT_VALUE = '127.0.0.1'
MONGO_PORT_DEFAULT_VALUE = 8001

AUTO_ACCEPT_NEW_USERS_ENV = 'AUTO_ACCEPT_NEW_USERS'
MONGO_MAX_USERS_ENV = 'MONGO_MAX_USERS'

AUTO_ACCEPT_NEW_USERS_DEFAULT = True
MONGO_MAX_USERS_DEFAULT = 100
